# Microservice CONFIGURATION

spring:
  
  application.name: one-service
  velocity.enabled: false

info.component: One-Service

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  contextPath: /manage

# Microservice Port
server:
  contextPath: /
  port: 8081

# Configure this Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
