# API-Gateaway Microservice CONFIGURATION

spring:
  application.name: api-gateway
  jmx.default-domain: ${spring.application.name}
  velocity.enabled: false

info.component: API-Gateway

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  contextPath: /manage

# Microservice Port
server:
  contextPath: /
  port: 8080

zuul:
  ignoredServices: '*'
  routes:
    one:
      path: /one-service/**
      serviceId: one-service
    two:
      path: /two-service/**
      serviceId: two-service

# Configure this Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
