# API-Gateaway Microservice CONFIGURATION

spring:
  
  application.name: api-gateway
  velocity.enabled: false

info.component: API-Gateway

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

management:
  contextPath: /manage

# Microservice Port
server:
  contextPath: /
  port: 8080

zuul:
  ignoredServices: '*'
  routes:
    one:
      path: /one-service/**
      serviceId: One-Service
    two:
      path: /two-service/**
      serviceId: Two-Service
    three:
      path: /three-service/**
      serviceId: Three-Service

# Configure this Discovery Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
